---
 - name: all yum tasks
   hosts: cassandranodes
   become: true
   var casspackages:
    - java 
    - dsc30 
    - cassandra30-tools 
    - ntp


   tasks:
     - name: install utils
       yum:
         name: yum-utils
         state: present
 
     - name: get repo
       yum_repository:
         name:  added from: http://rpm.datastax.com/community
         baseurl: http://rpm.datastax.com/community
         enabled: 1 

     - name: install packages
        yum:
         name: "{{item}}
         state: present
        loop: "{{cassspackages}}" 
       
